# Generated by Django 5.1.4 on 2024-12-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('prabhu', 'Prabhu'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips'), ('sct', 'SCT'), ('qr_code', 'QR Code'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_status',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('prabhu', 'Prabhu'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips'), ('sct', 'SCT'), ('qr_code', 'QR Code'), ('other', 'Other')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('prabhu', 'Prabhu'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips'), ('sct', 'SCT'), ('qr_code', 'QR Code'), ('other', 'Other')], max_length=20),
        ),
    ]
