# Generated by Django 5.1.4 on 2024-12-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_order_completed_by_orderhistory_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
