# Generated by Django 5.1.4 on 2024-12-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_order_delivery_charge_alter_menuitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('table', 'table'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('table', 'table'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=20),
        ),
    ]
