# Generated by Django 5.1.4 on 2024-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_order_order_type_alter_orderhistory_order_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order histories'},
        ),
        migrations.AlterModelOptions(
            name='orderhistoryitem',
            options={'ordering': ['order_history', 'item']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'item']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_edited']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('table', 'Table'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
