# Generated by Django 5.1.4 on 2025-01-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_remove_orderhistory_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('prabhu', 'Prabhu'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips'), ('sct', 'SCT'), ('qr_code', 'QR Code'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.orderhistory')),
            ],
        ),
    ]
